# Generated by Django 4.2.16 on 2024-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('party', 'Party'), ('corporate', 'Corporate')], max_length=50)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('guests', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('services', models.CharField(choices=[('Catering', 'Catering'), ('Decoration', 'Decoration'), ('Entertainment', 'Entertainment'), ('Photography', 'Photography'), ('Venue', 'Venue'), ('All', 'All')], max_length=50)),
                ('requests', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(max_length=13)),
            ],
        ),
    ]
